    - name: Bootstrap install epel epel debug
      copy: src=repo-bootstrap.repo
            dest=/etc/yum.repos.d/
            owner=root group=root mode=0644
    - name: epel repository enable
      ini_file: dest=/etc/yum.repos.d/repo-bootstrap.repo
                section=epel
                option=enabled
                value=1
    - name: epel-debug repository enable
      ini_file: dest=/etc/yum.repos.d/repo-bootstrap.repo
                section=epel-debuginfo
                option=enabled
                value=1
    - name: epel-source repository enable
      ini_file: dest=/etc/yum.repos.d/repo-bootstrap.repo
                section=epel-source
                option=enabled
                value=1
    - name: base repository enable
      ini_file: dest=/etc/yum.repos.d/repo-bootstrap.repo
                section=base
                option=enabled
                value=1
    - name: updates repository enable
      ini_file: dest=/etc/yum.repos.d/repo-bootstrap.repo
                section=updates
                option=enabled
                value=1
    - name: extras repository enable
      ini_file: dest=/etc/yum.repos.d/repo-bootstrap.repo
                section=extras
                option=enabled
                value=1
    - name: centosplus repository enable
      ini_file: dest=/etc/yum.repos.d/repo-bootstrap.repo
                section=centosplus
                option=enabled
                value=1
    - name: contrib repository enable
      ini_file: dest=/etc/yum.repos.d/repo-bootstrap.repo
                section=contrib
                option=enabled
                value=1
    - name: postgres repository enable
      ini_file: dest=/etc/yum.repos.d/repo-bootstrap.repo
                section=pgdg92
                option=enabled
                value=1
    - name: postgres source repository enable
      ini_file: dest=/etc/yum.repos.d/repo-bootstrap.repo
                section=pgdg92-source
                option=enabled
                value=1
    - name: Bootstrap install epel epel debug
      copy: src=customrepo.repo
            dest=/etc/yum.repos.d/
            owner=root group=root mode=0644
    - name: add custom repo
      ini_file: dest=/etc/yum.repos.d/customrepo.repo
                section=customrepo
                option=enabled
                value=1
    - name: Remove bootstrap repo
      file: path=/etc/yum.repos.d/repo-bootstrap.repo
            owner=root group=root mode=0644 state=absent